### ISSUE TITLE
ecs/initializer failed with django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

### ISSUE THREAD

**Issue by dkemper01** [DefectDojo/Community-Contribs#27]
Hello, and thank you for putting together this Fargate stack. I have spent some time w/ it and have made the necessary substitutions required to properly execute the template and successfully create the stack.

Problem: When I point my browser at the public IP on port 8080 and nginx handles my request, I receive an Internal Server Error message. Upon further inspection, in the CloudWatch log group for the ecs/initializer I found the following error:

    django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

Potential Solution: 

I believe the DD_SECRET_KEY, and perhaps even the DD_CREDENTIAL_AES_256_KEY environment variables are missing from the services/tasks that require it. Can you confirm as you find time?

**Comment by mtesauro** [comment]
I don't use Fargate or AWS/Cloudformation to run DefectDojo but I think I can help you.  Having written godojo and the previous setup.bash installers, DefectDojo absolutely needs to have DD_SECRET_KEY set to something reasonable - godojo uses 128 random characters.  Technically speaking, DD_CREDENTIAL_AES_256_KEY is only used by the credential manager inside DefectDojo (it encrypts any provided credentials prior to writing them to the DB) so if you don't use the credential manager, you don't _have_ to set it but it's a good idea to do it anyway.  godojo uses another 128 random characters for this as well. Depending on how you do the install/deploy, you can add a value in the environment or hard code it in local_settings.py (less optimal/secure).

I assume your issue is from the Cloudformation contribution at https://github.com/DefectDojo/Community-Contribs/tree/master/aws-deploy-cloudformation-fargate - that was donated to the project by a community member 3+ years ago. Like the rest of community-contribs, it's not actively maintained by the DefectDojo team.  

That said, if you find a solution for this issue, **PRs are happily accepted for this repo**.  Please consider giving back if you figure this out.

**Comment by mtesauro** [comment]
Excellent @dkemper01 

We'd love to have some hardening additions to the CF template. Best of luck.

I am going to go ahead and close this issue.  Feel free to reopen if needed.
